src/index.ejs, src/sass/index.sass
=> ✏ updating copy around 5DV

src/index.ejs
=> ✏ Add donation link for 5DV

src/index.ejs
=> ⏰ fixed a silly link

src/index.ejs
=> 🐛Link should open in new window

src/index.ejs
Fixes #20 
Data is viewable using `admin@5dv.nyc` @curieuxqueen
=> 🔧Adding google analytics

src/index.ejs
=> ✏ Add donation link for LSV

src/index.ejs, src/sass/_colors.sass, src/sass/_typography.sass, src/sass/index.sass
Added the banner to the top of the page, with associated styling.
=> Header update

src/sass/index.sass
Swapped order of LSV/ATL columns, per issue #28
=> Change order of LSV/ATL columns

src/index.ejs, src/sass/index.sass
=> 🐛Addressing visual regression for donation links

src/index.ejs
=> ✨Adding toronto donation link

src/index.ejs
=> ✨Add ATL donation link

src/sass/index.sass
=> 🎨More margins for the CTAs after text

src/index.ejs, src/sass/index.sass
References #48 
TODO
Image replacement with partner logos
=> ✨Add footer text.

src/sass/_colors.sass
Reset column colors per issue #62
=> Change column colors

src/index.ejs
=> ✨Add copy for LSV

src/index.ejs
=> ✏Update TAF link

src/index.ejs
=> ✏Update page title to reflect date

src/index.ejs, src/sass/index.sass
=> Add links to team twitter pages

src/sass/index.sass
=> 🎨Bring partner logo size down 25%

src/sass/_typography.sass
=> ✨Add display-swap stanza to google font imports

src/index.ejs
=> Apply tweaks to LSV copy

package-lock.json, package.json, webpack-config.common.js
Adds sitemap functionality, makes sure meta description is in place.
=> ✨General improvements to SEO

src/index.ejs, src/sass/index.sass
Altering header weight since we were missing an H1 on the page, as well as raising priority of other tags. Adding descriptions and keywording for each supporter's club, hiding text for aria readers.
=> ✏Add SEO fixes for headers and alt text

src/index.ejs
=> ✨ Update donation links for LSV and ATL
